# Generated by Django 2.2.12 on 2022-06-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_editor',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pdf_editor',
            name='file',
            field=models.FileField(default='Choose a file', upload_to='documents/'),
        ),
    ]
