# Generated by Django 2.2.12 on 2022-06-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0002_auto_20220607_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_editor',
            new_name='PDF_editorModel',
        ),
    ]
