# Generated by Django 2.2.12 on 2022-06-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0003_auto_20220607_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_editorModel',
            new_name='PDF_editorMode',
        ),
    ]
