# Generated by Django 2.2.12 on 2022-06-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0004_auto_20220607_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_editorMode',
            new_name='PdfEditorModel',
        ),
    ]
