# Generated by Django 4.0.6 on 2022-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0005_auto_20220607_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfChooseModifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PagesDuplicate', models.CharField(max_length=100)),
                ('PagesDuplicateCopies', models.IntegerField(default=1)),
                ('PagesDuplicateOption', models.CharField(choices=[('CP', 'Collate Pages'), ('JE', 'Join to End')], default='CP', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='pdfeditormodel',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
