# Generated by Django 4.0.6 on 2022-07-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_editor', '0006_pdfchoosemodifymodel_alter_pdfeditormodel_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfchoosemodifymodel',
            old_name='PagesDuplicateCopies',
            new_name='pages_duplicate_copies',
        ),
        migrations.RenameField(
            model_name='pdfchoosemodifymodel',
            old_name='PagesDuplicateOption',
            new_name='pages_duplicate_option',
        ),
        migrations.RenameField(
            model_name='pdfchoosemodifymodel',
            old_name='PagesDuplicate',
            new_name='pages_to_duplicate',
        ),
    ]
